---
abstract: 'Implementation of the HyperLogLog cardinality estimation algorithm'
author:
  - 'Hideaki Ohno<hide.o.j55@gmail.com>'
build_requires:
  ExtUtils::CBuilder: 0
  File::Temp: 0
  Module::Build::Pluggable::CPANfile: 0.04
  Module::Build::Pluggable::GithubMeta: 0
  Module::Build::Pluggable::ReadmeMarkdownFromPod: 0.04
  Module::Build::Pluggable::XSUtil: 1.01
  Pod::Markdown: 0
  Test::Fatal: 0.008
  Test::More: 0.98
configure_requires:
  Devel::CheckCompiler: 0.01
  ExtUtils::ParseXS: 2.21
  Module::Build: 0.4005
  Module::Build::Pluggable: 0
  Module::Build::Pluggable::CPANfile: 0.04
  Module::Build::Pluggable::GithubMeta: 0
  Module::Build::Pluggable::ReadmeMarkdownFromPod: 0.04
  Module::Build::Pluggable::XSUtil: 1.01
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
keywords:
  - HyperLogLog
  - cardinality
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-HyperLogLog
no_index:
  directory:
    - t
    - xt
    - inc
    - eg
provides:
  Algorithm::HyperLogLog:
    file: lib/Algorithm/HyperLogLog.pm
    version: 0.19
  Algorithm::HyperLogLog::PP:
    file: lib/Algorithm/HyperLogLog/PP.pm
    version: 0.19
requires:
  Carp: 0
  Digest::MurmurHash3::PurePerl: 0.02
  XSLoader: 0.02
  perl: 5.008008
resources:
  bugtracker: https://github.icom/hideo55/p5-Algorithm-HyperLogLog/issues
  homepage: https://github.com/hideo55/p5-Algorithm-HyperLogLog/tree
  repository: git://github.com/hideo55/p5-Algorithm-HyperLogLog.git
version: 0.19
